Write exceptions to stderr in case sending to cd4pe fails
If an exception is thrown while setting up the job runner, I get
```
run_cd4pe_job.rb:517:in `rescue in <main>': undefined method `send_job_output_to_cd4pe' for nil:NilClass (NoMethodError)
  from run_cd4pe_job.rb:473:in `<main>'
```
which is not particularly useful. The exception and all logs are lost.